[build]
  base = "website"
  command = "npm run build"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF HEAD -- ../taxa.csv ."

[[headers]]
  for = "/taxa-images/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/explore/*"
  to = "/index.html"
  status = 200
